import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { SchemaDescription, SchemaLike } from "../validation/Schema";
import type { RouteOpenApiOptions } from "./OpenApi";
import type { RegisteredRoute, Router, RouteSchemaOptions } from "./Router";

type ApiClientHeadersInit = NonNullable<RequestInit["headers"]>;
type ApiClientBodyInit = NonNullable<RequestInit["body"]>;
type ApiClientRequestCredentials = NonNullable<RequestInit["credentials"]>;
export type ApiClientFetch = (
	input: Parameters<typeof fetch>[0],
	init?: Parameters<typeof fetch>[1],
) => ReturnType<typeof fetch>;

export type ApiClientPrimitive = string | number | boolean | Date;
export type ApiClientQueryValue =
	| ApiClientPrimitive
	| null
	| undefined
	| readonly (ApiClientPrimitive | null | undefined)[];

export type ApiClientRoute = {
	readonly method: string;
	readonly path: string;
	readonly bodyKind?: "json" | "multipart";
};

export type ApiClientRequestOptions = {
	readonly params?: Record<string, ApiClientPrimitive>;
	readonly query?: Record<string, ApiClientQueryValue>;
	readonly headers?: ApiClientHeadersInit;
	readonly body?: unknown;
	readonly signal?: AbortSignal;
};

export type ApiClientOptions = {
	readonly baseUrl?: string | URL;
	readonly fetch?: ApiClientFetch;
	readonly headers?: ApiClientHeadersInit;
	readonly credentials?: ApiClientRequestCredentials;
};

export class ApiClientError<TData = unknown> extends Error {
	override readonly name = "ApiClientError";

	constructor(
		message: string,
		readonly response: Response,
		readonly data: TData | undefined,
	) {
		super(message);
	}

	get status(): number {
		return this.response.status;
	}
}

export type ApiClientRuntime = {
	request<TResponse>(
		route: ApiClientRoute,
		options?: ApiClientRequestOptions,
	): Promise<TResponse>;
};

export function createApiClient(
	options: ApiClientOptions = {},
): ApiClientRuntime {
	const baseUrl = options.baseUrl ?? "http://localhost";
	const fetcher = options.fetch ?? fetch;
	const baseHeaders = new Headers(options.headers);

	return {
		async request<TResponse>(
			route: ApiClientRoute,
			requestOptions: ApiClientRequestOptions = {},
		): Promise<TResponse> {
			const url = buildApiClientUrl(baseUrl, route.path, requestOptions);
			const headers = new Headers(baseHeaders);

			for (const [name, value] of new Headers(
				requestOptions.headers,
			).entries()) {
				headers.set(name, value);
			}

			const body = serializeApiClientBody(route, requestOptions.body, headers);
			const response = await fetcher(url, {
				method: route.method,
				headers,
				body,
				credentials: options.credentials,
				signal: requestOptions.signal,
			});
			const data = await readApiClientResponse(response);

			if (!response.ok) {
				throw new ApiClientError(
					`Request failed with status ${response.status}`,
					response,
					data,
				);
			}

			return data as TResponse;
		},
	};
}

export type GenerateTypedApiClientOptions = {
	readonly importPath?: string;
	readonly clientFactoryName?: string;
};

export type WriteTypedApiClientOptions = GenerateTypedApiClientOptions & {
	readonly output: string;
};

type RouteTypeParts = {
	readonly methodName: string;
	readonly route: RegisteredRoute;
	readonly paramsType: string | null;
	readonly queryType: string | null;
	readonly headersType: string | null;
	readonly bodyType: string | null;
	readonly responseType: string;
	readonly bodyKind?: "json" | "multipart";
	readonly requiresOptions: boolean;
};

type ResponseSchemaCandidate = {
	readonly status: number;
	readonly schema: SchemaLike<unknown>;
};

const DEFAULT_CLIENT_IMPORT_PATH = "kura/client";
const DEFAULT_CLIENT_FACTORY_NAME = "createApi";
const reservedMethodNames = new Set([
	"constructor",
	"then",
	"catch",
	"finally",
]);

export function generateTypedApiClient(
	router: Router,
	options: GenerateTypedApiClientOptions = {},
): string {
	const importPath = options.importPath ?? DEFAULT_CLIENT_IMPORT_PATH;
	const clientFactoryName =
		options.clientFactoryName ?? DEFAULT_CLIENT_FACTORY_NAME;
	const routes = router.list().filter((route) => !route.openapi?.hidden);
	const routeParts = createRouteTypeParts(routes);

	return [
		"/* eslint-disable */",
		"// Generated by Kura. Do not edit this file manually.",
		`import { createApiClient, type ApiClientOptions } from ${JSON.stringify(importPath)};`,
		"",
		...routeParts.flatMap(renderRouteTypes),
		`export function ${clientFactoryName}(options: ApiClientOptions = {}) {`,
		"\tconst client = createApiClient(options);",
		"",
		"\treturn {",
		...routeParts.map(renderRouteMethod),
		"\t};",
		"}",
		"",
		`export type ApiClient = ReturnType<typeof ${clientFactoryName}>;`,
		"",
	].join("\n");
}

export async function writeTypedApiClient(
	router: Router,
	options: WriteTypedApiClientOptions,
): Promise<void> {
	await mkdir(dirname(options.output), { recursive: true });
	await writeFile(options.output, generateTypedApiClient(router, options));
}

function buildApiClientUrl(
	baseUrl: string | URL,
	path: string,
	options: ApiClientRequestOptions,
): string {
	const resolvedPath = path.replace(/:(\w+)/g, (_, key: string) => {
		const value = options.params?.[key];

		if (value === undefined) {
			throw new Error(`Missing route parameter [${key}]`);
		}

		return encodeURIComponent(formatApiClientValue(value));
	});
	const url = new URL(resolvedPath, baseUrl);

	for (const [key, value] of Object.entries(options.query ?? {})) {
		if (isReadonlyArray(value)) {
			for (const item of value) {
				appendApiClientQueryValue(url, key, item);
			}
		} else {
			appendApiClientQueryValue(url, key, value);
		}
	}

	return url.toString();
}

function appendApiClientQueryValue(
	url: URL,
	key: string,
	value: ApiClientPrimitive | null | undefined,
): void {
	if (value === undefined || value === null) {
		return;
	}

	url.searchParams.append(key, formatApiClientValue(value));
}

function formatApiClientValue(value: ApiClientPrimitive): string {
	return value instanceof Date ? value.toISOString() : String(value);
}

function serializeApiClientBody(
	route: ApiClientRoute,
	body: unknown,
	headers: Headers,
): ApiClientBodyInit | undefined {
	if (body === undefined || route.method === "GET" || route.method === "HEAD") {
		return undefined;
	}

	if (isBodyInit(body)) {
		return body;
	}

	if (route.bodyKind === "multipart") {
		return objectToFormData(body);
	}

	if (!headers.has("Content-Type")) {
		headers.set("Content-Type", "application/json");
	}

	return JSON.stringify(body);
}

function isBodyInit(value: unknown): value is ApiClientBodyInit {
	return (
		typeof value === "string" ||
		value instanceof ArrayBuffer ||
		value instanceof Blob ||
		value instanceof FormData ||
		value instanceof URLSearchParams ||
		value instanceof ReadableStream
	);
}

function objectToFormData(value: unknown): FormData {
	if (value instanceof FormData) {
		return value;
	}

	if (!isRecord(value)) {
		throw new Error("Multipart request body must be an object or FormData");
	}

	const formData = new FormData();
	for (const [key, fieldValue] of Object.entries(value)) {
		appendFormDataValue(formData, key, fieldValue);
	}

	return formData;
}

function appendFormDataValue(
	formData: FormData,
	key: string,
	value: unknown,
): void {
	if (value === undefined || value === null) {
		return;
	}

	if (Array.isArray(value)) {
		for (const item of value) {
			appendFormDataValue(formData, key, item);
		}
		return;
	}

	if (value instanceof Blob) {
		formData.append(key, value);
		return;
	}

	formData.append(key, String(value));
}

async function readApiClientResponse(response: Response): Promise<unknown> {
	if (response.status === 204) {
		return undefined;
	}

	const contentType = response.headers.get("Content-Type") ?? "";
	if (contentType.toLowerCase().includes("application/json")) {
		return response.json();
	}

	return response.text();
}

function createRouteTypeParts(
	routes: readonly RegisteredRoute[],
): readonly RouteTypeParts[] {
	const usedNames = new Set<string>();

	return routes.map((route) => {
		const methodName = uniqueMethodName(routeMethodName(route), usedNames);
		const paramsDescription = describeSchema(route.schema?.params);
		const queryDescription = describeSchema(route.schema?.query);
		const headersDescription = describeSchema(route.schema?.headers);
		const bodyDescription = describeSchema(route.schema?.body);
		const paramsType =
			paramsDescription || route.params.length > 0
				? schemaOrPathParamsToType(paramsDescription, route.params)
				: null;
		const queryType = schemaDescriptionToType(queryDescription, "input");
		const headersType = schemaDescriptionToType(headersDescription, "input");
		const bodyType = schemaDescriptionToType(bodyDescription, "input");
		const responseType = schemaDescriptionToType(
			describeResponseSchema(route),
			"output",
		);
		const bodyKind = bodyDescription
			? schemaContainsFile(bodyDescription)
				? "multipart"
				: "json"
			: undefined;

		return {
			methodName,
			route,
			paramsType,
			queryType,
			headersType,
			bodyType,
			responseType: responseType ?? "unknown",
			bodyKind,
			requiresOptions:
				Boolean(paramsType) ||
				schemaPartIsRequired(queryDescription) ||
				schemaPartIsRequired(headersDescription) ||
				schemaPartIsRequired(bodyDescription),
		};
	});
}

function renderRouteTypes(parts: RouteTypeParts): readonly string[] {
	const typePrefix = pascalCase(parts.methodName);
	const lines: string[] = [];

	if (parts.paramsType) {
		lines.push(`export type ${typePrefix}Params = ${parts.paramsType};`, "");
	}

	if (parts.queryType) {
		lines.push(`export type ${typePrefix}Query = ${parts.queryType};`, "");
	}

	if (parts.headersType) {
		lines.push(`export type ${typePrefix}Headers = ${parts.headersType};`, "");
	}

	if (parts.bodyType) {
		lines.push(`export type ${typePrefix}Body = ${parts.bodyType};`, "");
	}

	lines.push(`export type ${typePrefix}Response = ${parts.responseType};`, "");
	lines.push(
		`export type ${typePrefix}Options = ${renderOptionsType(parts)};`,
		"",
	);

	return lines;
}

function renderRouteMethod(parts: RouteTypeParts): string {
	const typePrefix = pascalCase(parts.methodName);
	const optionsParameter = parts.requiresOptions
		? `options: ${typePrefix}Options`
		: `options: ${typePrefix}Options = {}`;
	const route = JSON.stringify({
		method: parts.route.method,
		path: parts.route.path,
		bodyKind: parts.bodyKind,
	});

	return `\t\t${parts.methodName}: (${optionsParameter}) => client.request<${typePrefix}Response>(${route}, options),`;
}

function renderOptionsType(parts: RouteTypeParts): string {
	const fields: string[] = [];

	if (parts.paramsType) {
		fields.push(`params: ${pascalCase(parts.methodName)}Params`);
	}

	if (parts.queryType) {
		fields.push(
			`${schemaPartIsRequired(describeSchema(parts.route.schema?.query)) ? "query" : "query?"}: ${pascalCase(parts.methodName)}Query`,
		);
	}

	if (parts.headersType) {
		fields.push(
			`${schemaPartIsRequired(describeSchema(parts.route.schema?.headers)) ? "headers" : "headers?"}: ${pascalCase(parts.methodName)}Headers`,
		);
	}

	if (parts.bodyType) {
		fields.push(
			`${schemaPartIsRequired(describeSchema(parts.route.schema?.body)) ? "body" : "body?"}: ${pascalCase(parts.methodName)}Body`,
		);
	}

	fields.push("signal?: AbortSignal");

	return fields.length === 0
		? "Record<string, never>"
		: `{\n${fields.map((field) => `\t${field};`).join("\n")}\n}`;
}

function routeMethodName(route: RegisteredRoute): string {
	return camelCase(
		route.openapi?.operationId ?? route.name ?? routePathMethodName(route),
	);
}

function routePathMethodName(route: RegisteredRoute): string {
	const pathName = route.path
		.split("/")
		.filter(Boolean)
		.map((segment) =>
			segment.startsWith(":") ? `by-${segment.slice(1)}` : segment,
		)
		.join("-");

	return `${route.method.toLowerCase()}-${pathName || "root"}`;
}

function uniqueMethodName(name: string, usedNames: Set<string>): string {
	const fallback = reservedMethodNames.has(name) ? `${name}Route` : name;
	let candidate = fallback;
	let index = 2;

	while (usedNames.has(candidate)) {
		candidate = `${fallback}${index}`;
		index += 1;
	}

	usedNames.add(candidate);
	return candidate;
}

function schemaOrPathParamsToType(
	description: SchemaDescription | null,
	pathParams: readonly string[],
): string {
	if (description?.type === "object") {
		return schemaObjectToType(
			{
				...description,
				shape: {
					...(description.shape ?? {}),
					...Object.fromEntries(
						pathParams
							.filter((param) => !description.shape?.[param])
							.map((param) => [
								param,
								{
									type: "string",
									optional: false,
									nullable: false,
								} satisfies SchemaDescription,
							]),
					),
				},
			},
			"input",
		);
	}

	const schemaType = schemaDescriptionToType(description, "input");
	if (schemaType) {
		return schemaType;
	}

	const fields = pathParams.map(
		(param) => `\t${quoteProperty(param)}: string | number;`,
	);
	return `{\n${fields.join("\n")}\n}`;
}

function describeSchema(
	schema: SchemaLike<unknown> | undefined,
): SchemaDescription | null {
	return schema ? schema.describe() : null;
}

function describeResponseSchema(
	route: RegisteredRoute,
): SchemaDescription | null {
	const candidates = [
		...responseSchemaCandidates(route.schema?.responses),
		...responseSchemaCandidates(route.openapi?.responses),
	].sort((left, right) => left.status - right.status);
	const candidate =
		candidates.find((item) => item.status === 200) ??
		candidates.find((item) => item.status === 201) ??
		candidates.find((item) => item.status >= 200 && item.status < 300);

	return candidate?.schema.describe() ?? null;
}

function responseSchemaCandidates(
	responses:
		| RouteSchemaOptions["responses"]
		| RouteOpenApiOptions["responses"]
		| undefined,
): readonly ResponseSchemaCandidate[] {
	if (!responses) {
		return [];
	}

	return Object.entries(responses).flatMap(([status, response]) => {
		const statusNumber = Number(status);
		const schema = responseSchema(response);

		return Number.isFinite(statusNumber) && schema
			? [{ status: statusNumber, schema }]
			: [];
	});
}

function responseSchema(response: unknown): SchemaLike<unknown> | null {
	if (isSchemaLike(response)) {
		return response;
	}

	if (isRecord(response) && isSchemaLike(response.body)) {
		return response.body;
	}

	return null;
}

function schemaDescriptionToType(
	description: SchemaDescription | null,
	mode: "input" | "output",
): string | null {
	if (!description) {
		return null;
	}

	const base = schemaDescriptionBaseType(description, mode);
	return description.nullable ? `${base} | null` : base;
}

function schemaDescriptionBaseType(
	description: SchemaDescription,
	mode: "input" | "output",
): string {
	if (description.values) {
		return description.values.map((value) => JSON.stringify(value)).join(" | ");
	}

	switch (description.type) {
		case "string":
			return "string";
		case "number":
			return "number";
		case "boolean":
			return "boolean";
		case "date":
			return mode === "input" ? "Date | string" : "string";
		case "file":
			return "File";
		case "array": {
			const item =
				schemaDescriptionToType(description.item ?? null, mode) ?? "unknown";
			return `(${item})[]`;
		}
		case "object":
			return schemaObjectToType(description, mode);
		default:
			return "unknown";
	}
}

function schemaObjectToType(
	description: SchemaDescription,
	mode: "input" | "output",
): string {
	const shape = description.shape ?? {};
	const fields = Object.entries(shape).map(([key, field]) => {
		const fieldType = schemaDescriptionToType(field, mode) ?? "unknown";
		return `\t${quoteProperty(key)}${field.optional ? "?" : ""}: ${fieldType};`;
	});

	return fields.length > 0
		? `{\n${fields.join("\n")}\n}`
		: "Record<string, never>";
}

function schemaPartIsRequired(description: SchemaDescription | null): boolean {
	if (!description || description.optional) {
		return false;
	}

	if (description.type !== "object" || !description.shape) {
		return true;
	}

	return Object.values(description.shape).some((field) => !field.optional);
}

function schemaContainsFile(description: SchemaDescription): boolean {
	if (description.type === "file") {
		return true;
	}

	if (description.item && schemaContainsFile(description.item)) {
		return true;
	}

	return Object.values(description.shape ?? {}).some(schemaContainsFile);
}

function quoteProperty(name: string): string {
	return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

function camelCase(value: string): string {
	const words = wordsFromValue(value);
	const [first = "route", ...rest] = words;
	return [
		first.toLowerCase(),
		...rest.map(
			(word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase(),
		),
	].join("");
}

function pascalCase(value: string): string {
	const words = wordsFromValue(value);
	return words
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
		.join("");
}

function wordsFromValue(value: string): string[] {
	const words = value
		.replace(/([a-z0-9])([A-Z])/g, "$1 $2")
		.split(/[^A-Za-z0-9]+/)
		.filter(Boolean);

	return words.length > 0 ? words : ["route"];
}

function isSchemaLike(value: unknown): value is SchemaLike<unknown> {
	return (
		isRecord(value) &&
		typeof value.parse === "function" &&
		typeof value.parseAsync === "function" &&
		typeof value.describe === "function"
	);
}

function isReadonlyArray(value: unknown): value is readonly unknown[] {
	return Array.isArray(value);
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}
